### ISSUE TITLE
undefined values should be undefined not 'undefined'

### ISSUE THREAD

**Issue by arkarkark** [jsok/karma-env-preprocessor#1]
It'd be nice if variables that are not set in the environment are undefined in the **env** object too. right now they might be set to the string 'undefined'

**Comment by Kagami** [comment]
:+1:
Right now `!!process.env.VAR` is `false` if `VAR` is not defined but `!!window.__env__.VAR` is `true`. That kind of behavior is confusing.

**Comment by jsok** [comment]
Let me know if the PR addresses this issue.
I wasn't sure if process.env.FOO is undefined or null when $FOO is an empty env var.

**Comment by Kagami** [comment]
LGTM.

``` js
$ node -e 'console.log(process.env.TEST, typeof process.env.TEST)'
undefined 'undefined'
$ TEST= node -e 'console.log(process.env.TEST, typeof process.env.TEST)' 
 string
$ TEST=1 node -e 'console.log(process.env.TEST, typeof process.env.TEST)'
1 string
```

**Comment by Kagami** [comment]
Oops, missed one thing actually. Commented in PR.
